# Generated by Django 5.2.1 on 2025-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_producto_costo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DISTRIBUIDOR", "Distribuidor"),
                    ("REVENDEDOR", "Revendedor"),
                    ("SUPERUSUARIO", "Superusuario"),
                ],
                default="DISTRIBUIDOR",
                max_length=20,
            ),
        ),
    ]
