# Generated by Django 5.2.1 on 2025-05-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customuser_rol"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarritoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("fecha_agregado", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(max_length=40)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producto"
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_agregado"],
            },
        ),
    ]
