# Generated by Django 5.2.1 on 2025-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_customuser_dni_customuser_domicilio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DISTRIBUIDOR", "Distribuidor"),
                    ("REVENDEDOR", "Revendedor"),
                    ("SUPERUSUARIO", "Superusuario"),
                    ("CLIENTE", "Cliente"),
                ],
                default="CLIENTE",
                max_length=20,
            ),
        ),
    ]
