# Generated by Django 5.2.1 on 2025-05-30 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_customuser_rol"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venta",
            options={"ordering": ["-fecha_venta"]},
        ),
        migrations.AddField(
            model_name="venta",
            name="comprador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compras",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="nombre_comprador",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("PAGADO", "Pagado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
