# Generated by Django 5.2.1 on 2025-06-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_venta_options_venta_comprador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio_distribuidor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_revendedor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
