# Generated by Django 5.2.2 on 2025-06-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_producto_precio_distribuidor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="domicilio",
            new_name="ciudad",
        ),
        migrations.AddField(
            model_name="producto",
            name="es_exclusivo",
            field=models.BooleanField(default=False),
        ),
    ]
