# Generated by Django 5.2.2 on 2025-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_session_key_to_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="es_distribuidor_exclusivo",
            field=models.BooleanField(default=False),
        ),
    ]
